name = "Terminal"
license = "MIT"
licenselink = ""
description = "A minimal ncurses-inspired terminal theme"
homepage = ""
tags = ["terminal", "dark", "minimal", "ncurses"]
features = ["responsive", "dark mode"]
min_version = "0.41.0"

[author]
  name = "gnome"
  homepage = ""