baseURL = 'https://gnomegl.github.io/'
languageCode = 'en-us'
title = 'gnome@gl'
theme = 'terminal'

[params]
  author = "gnome"
  description = "terminal-based osint tools and utilities"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      hardWraps = true
  [markup.highlight]
    style = 'terminal'
    lineNos = true
    lineNumbersInTable = true
